export const SET_FORM_FIELD_VALUE = 'SET_FORM_FIELD_VALUE';
export const SET_FORM_FIELD_ERROR = 'SET_FORM_FIELD_ERROR';
export const SET_INITIAL_FORM_VALUE = 'SET_INITIAL_FORM_VALUE';
export const SUBMIT_FORM = 'SUBMIT_FORM';
